Update CODEOWNERS
ChainSafe/ssz pull request #230
Opened 2022-02-08 16:07 UTC by wemeetagain

2022-02-13 02:42 UTC, tuyennhv approved these changes

2022-02-13 04:33 UTC, dapplion requested changes
Missing Gajinder and Dade, can you please setup a eth2 dev team with everyone and commit that? https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams

2022-02-13 17:22 UTC, wemeetagain commented
I don't have permission.
@GregTheGreek can you help?

2022-04-13 09:41 UTC, dapplion commented
Closing for https://github.com/ChainSafe/ssz/pull/253

2022-04-13 09:41 UTC, closed without merging